account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("login", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("register", views.user_register, name="register"),
    path("edit", views.user_edit, name="edit"),
]

blog/urls.py
from django.urls import path
from . import views

# /articles/
app_name = "blog"
urlpatterns = [
    path('detail/<slug:slug>', views.article_detail, name="article_detail"),
    path('list', views.article_list, name="articles_list"),
    path('list2', views.ArticleList.as_view(), name="articles_list2"),
    path('category/<int:pk>', views.category_detail, name="category_detail"),
    path('search', views.search, name="search_articles"),
    path('contactus', views.contactus, name="contact_us"),
    path('testbase', views.TestBaseView.as_view(), name="test_base"),
    path('ali', views.HelloToAli.as_view(), name="test_ali"),
    path('karim', views.HelloToKarim.as_view(), name="test_karim"),
    path('users', views.UserList.as_view(), name="user_list"),
    path('red/<slug:slug>', views.HomePageRedirect.as_view(), name="redirect"),
    path('messages', views.MessageView.as_view(), name="messages"),
    path('message_list', views.MessagesListView.as_view(), name="message_list"),
    path('message/edit/<int:pk>', views.MessageUpdateView.as_view(), name="message_edit"),
    path('message/delete/<int:pk>', views.MessageDeleteView.as_view(), name="message_delete"),
    path('archive', views.ArchiveIndexArticleView.as_view(), name="archive"),
    path('archive/<int:year>', views.YearArchiveArticleView.as_view(), name="archive_year"),
    path('like/<slug:slug>/<int:pk>', views.like, name="like"),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('home_app.urls')),
    path('', include('account.urls')),
    path('articles/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from typing import Iterable, Optional
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify
from datetime import datetime

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ArticleManager(models.Manager):
    def get_queryset(self):
        return super(ArticleManager, self).get_queryset().filter(status=True)


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="articles")
    category = models.ManyToManyField(Category, related_name="articles")
    title = models.CharField(max_length=70, unique_for_date="pub_date")
    body = models.TextField()
    image = models.ImageField(upload_to="images/articles")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    pub_date = models.DateTimeField(default=timezone.now())
    floatfield = models.FloatField(default=1)
    myfile = models.FileField(upload_to='test', null=True)
    status = models.BooleanField(default=True)
    published = models.BooleanField(default=True)
    slug = models.SlugField(blank=True, unique=True)
    objects = models.Manager()
    custom_manager = ArticleManager()

    # is_published = models.DurationField(default=timezone.timedelta(days=23, hours=21, minutes=43, seconds=54))

    # class Meta:
    #     ordering = ('-updated', '-created',) # ended with a comma to tell django it's a tuple.
    #     # It could also be : ['-created']
    #     verbose_name = "post" # So 'post' is used instead of the word 'article' in the control panel
    #     verbose_name_plural = "stories"

    # def save(self, force_insert: False, force_update: False, using: None, update_fields: None):
    #     self.slug = slugify(self.title)
    #     super(Article, self).save(force_insert, force_update, using, update_fields)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:article_detail", kwargs={"slug": self.slug}) #The value may be:articles/detail/3              The previous was kwargs={title": self.title}
        # return reverse("blog:article_detail", args=[self.id]) 
        # We could have used kwargs instead of args:  kwargs={'pk': self.id}

    def __str__(self):
        return f"{self.title} - {self.body[:30]}"
    

    class Meta:
        ordering = ("-created",)



# From article to comments: rabeteye maaxus: article.comments.all()

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments') # from comment to article: comment.article
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.body[:50]







        
class Message(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    email = models.EmailField()
    age = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    date = models.DateTimeField(default=timezone.now())
    
  
    
    def __str__(self):
        return self.title         



class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes", verbose_name="کاربر")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="likes", verbose_name="مقاله")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.article.title}"
    
    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "لایک ها"
        ordering = ('-created_at',)

blog/forms.py
from django import forms
from django.core.validators import ValidationError
from .models import Message



class ContactUsForm(forms.Form):
    BIRTH_YEAR_CHOISES = ['1980', '1981', '1982']
    FAVORITE_COLORS_CHOISES = [
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('black', 'Black'),
    ]
    name = forms.CharField(max_length=20, label='your name')
    text = forms.CharField(max_length=500, label='your message')
    birth_year = forms.DateField(widget=forms.SelectDateWidget(years=BIRTH_YEAR_CHOISES, attrs={'class': 'form-control'}))
    colors = forms.MultipleChoiceField(widget=forms.RadioSelect(), choices=FAVORITE_COLORS_CHOISES)

    def clean(self):
        name = self.cleaned_data.get('name')
        text = self.cleaned_data.get('text')
        # if 'a' in name:
        #     self.add_error('name', 'The letter a is not allowed in name')
        if name == text:
            raise ValidationError('The name and the text are the same', code='name_text_same')
        
    # def clean_name(self):
    #     name = self.cleaned_data.get('name')    
    #     if 'a' in name:
    #         raise ValidationError('The letter a is not allowed in name', code='a_in_name')


# class MessageForm(forms.Form):
#     title = forms.CharField(max_length=100)
#     text = forms.CharField(widget=forms.Textarea())
#     email = forms.EmailField()
#     age = forms.IntegerField()

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        # fields = '__all__'
        fields = ('title', 'text')

blog/views.py
from typing import Any, Optional
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from blog.models import Article, Category, Comment, Message, Like
from django.core.paginator import Paginator
from .forms import ContactUsForm, MessageForm
from django.views.generic.base import View, TemplateView, RedirectView
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, FormView, CreateView, UpdateView, DeleteView, ArchiveIndexView, YearArchiveView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse

# Create your views here.


def article_detail(request, slug):
    # article = Article.objects.get(id=pk)
    article = get_object_or_404(Article, slug=slug) #The previous version was title=title
    if request.method == 'POST':
        body = request.POST.get('body')
        Comment.objects.create(body=body, article=article, user=request.user)
    return render(request, "blog/article_details.html", {"article": article})


#def article_detail(request, pk):
    # article = Article.objects.get(id=pk)
    # article = get_object_or_404(Article, id=pk)
    # return render(request, "blog/article_details.html", {"article": article})


def article_list(request):  
    articles = Article.objects.all()
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 1)
    objects_list = paginator.get_page(page_number)
    return render(request, "blog/articles_list.html", {"articles": objects_list})


def category_detail(request, pk=None):
    category = get_object_or_404(Category, id=pk)
    # articles = category.article_set.all() We changed the name in the Article class to "articles"
    articles = category.articles.all()
    return render(request, "blog/articles_list.html", {"articles": articles})



def search(request):
    q = request.GET.get('q')
    articles = Article.objects.filter(title__icontains=q)
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 1)
    objects_list = paginator.get_page(page_number)
    return render(request, "blog/articles_list.html", {"articles": objects_list})



def contactus(request):
    if request.method == 'POST':
        
        form = MessageForm(data=request.POST)
        if form.is_valid():
            # return redirect('home_app:main') We wanna stay in the same page.
            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            email = form.cleaned_data['email']
            Message.objects.create(title=title, text=text, email=email)
            # form.save() Alternative to writing all fields

    else:
        form = MessageForm()
    return render(request, "blog/contact_us.html", {'form': form})




class TestBaseView(View):
    name = "Ciawash"
    def get(self, request):
        return HttpResponse(self.name)
    


class HelloToAli(TestBaseView):
    name = "ali"



class HelloToKarim(TestBaseView):
    name = "karim"



# class ListView(View): We no longer need it because we imported the whole package
#     queryset = None
#     template_name = None

#     def get(self, request):
#         return render(request, self.template_name, {'object_list': self.queryset})
    


# class ArticleList(ListView):
#     queryset = Article.objects.all()
#     template_name = "blog/articles_list.html"



class UserList(ListView):
    queryset = User.objects.all()
    template_name = "blog/user_list.html"



class ArticleList(TemplateView):
    model = Article
    # context_object_name = "articles" It must be converted to object_list or this attribute could be removed. Watch the relevant video!
    paginate_by = 1
    template_name = "blog/articles_list2.html"
    queryset = Article.objects.filter(published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = Article.objects.all() 
        return context
    

class HomePageRedirect(RedirectView):
    # url = "/articles/list" We could also use the pattern_name:
    pattern_name = "blog:article_detail"
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        print(self.request.user.username)
        return super().get_redirect_url(*args, **kwargs)
    



class ContactUsView(FormView):
    template_name = "blog/contact_us.html"
    form_class = MessageForm
    # success_url = "/"  We could have used this:
    # success_url = reverse(home_app:main) But because of bookmark 4, we use this:
    success_url = reverse_lazy("home_app:main")

    def form_valid(self, form):
        form_data = form.cleaned_data
        # Message.objects.create(title=form_data["title"]) Instead we use this:
        Message.objects.create(**form_data)
        return super().form_valid(form)



class MessageView(CreateView):
    model = Message
    # fields = ('title', 'text') Instead of manually typing all fields, we can use this:
    # fields = "__all__"
    fields = ('title', 'text', 'date', 'age')
    success_url = reverse_lazy('home_app:main')
    # template_name = "blog" As the name rules are followed, we don't need this

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["messages"] = Message.objects.all() 
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.email = self.request.user.email
        instance.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        print(self.object)
        return super(MessageView).get_success_url()
    


class MessagesListView(ListView):
    model = Message


class MessageUpdateView(UpdateView):
    model = Message
    fields = ('title', 'text', 'age') # Fields that you'd like to change
    template_name_suffix = "_update_form" # We could also have used this:
    # template_name = "blog/message_update_form.html"
    success_url = reverse_lazy("blog:message_list")



class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy("blog:message_list")



class ArchiveIndexArticleView(ArchiveIndexView):
    model = Article
    date_field = "updated"



class YearArchiveArticleView(YearArchiveView):
    model = Article
    date_field = "pub_date"
    make_object_list = True
    allow_future = True
    # template_name = "blog/article_archive_year.html"


    

def like(request, slug, pk):
    try:
        like = Like.objects.get(article__slug=slug, user_id=request.user.id)
        like.delete()
        return JsonResponse({"response": "unliked"})

    except:
        Like.objects.create(article_id=pk, user_id=request.user.id) 
        return JsonResponse({"response": "liked"})

   

blog/templates/blog/article_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Article archive</title>
</head>
<body>
    <ul>
        {% for article in latest %}
            <li>{{ article.updated }}: {{ article.title }}</li>
        {% endfor %}
    </ul>
</body>
</html>

blog/templates/blog/article_archive_year.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yearly archive</title>
</head>
<body>
    <ul>
        {% for date in date_list %}
            <li>{{ date|date }}</li>
        {% endfor %}
    </ul>
    
    <div>
        <h1>All Articles for {{ year|date:"Y" }}</h1>
        {% for obj in object_list %}
            <p>
                {{ obj.title }} - {{ obj.pub_date|date:"F j, Y" }} - {{ next_year }}
            </p>
        {% endfor %}
    </div>
</body>
</html>

blog/templates/blog/article_details.html
{% extends "home_app/base.html" %}
{% load static %}

{% block title %}
    {{ article.title }}
{% endblock title %}

{% block content %}
        <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Article Details</h4>
                <h2>{{ article.title }}</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{ article.image.url }}" alt="">
                    </div>
                    <div class="down-content">
                      <span>Lifestyle</span>
                      <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ article.author.get_full_name }}</a></li>
                        <li><a href="#">{{ article.created }}</a></li>
                        <li><a href="#">10 Comments</a></li>
                      </ul>
                      <p>{{ article.body }}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              {% if is_liked %}
                              <li><a onclick="like('{{ article.slug }}', '{{ article.id }}')"><i id="like" style="font-size: 20px" class="fa fa-heart"></i></a><span id="count">{{ article.likes.all.count }}</span></li>
                              {% else %}
                              <li><a onclick="like('{{ article.slug }}', '{{ article.id }}')"><i id="like" style="font-size: 20px" class="fa fa-heart-o"></i></a><span id="count">{{ article.likes.all.count }}</span></li>
                              {% endif %}
                              
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2>4 comments</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for comment in article.comments.all %}
                            {% if comment.parent == None %}
                            <li>
                              <div class="author-thumb">
                                {% if comment.user.profile.image %}
                                      <img src="{{ comment.user.profile.image.url }}" alt="">
                                      {% else %}
                                      <img src="{% static 'images/icons/defaultprofileimage.png' %}" alt="">
                                    {% endif %}
                              </div>
                              <div class="right-content">
                                <h4>{{ comment.user.get_full_name }}<span>{{ comment.created_at }}</span></h4>
                                <p>{{ comment.body }}</p>
                                <button onclick="set_value({{ comment.id }})" class="btn btn-primary">reply</button>
                              </div>
                            </li>
                                {% for reply in comment.replies.all %}
                                <li class="replied">
                                  <div class="author-thumb">
                                    {% if comment.user.profile.image %}
                                      <img src="{{ comment.user.profile.image.url }}" alt="">
                                      {% else %}
                                      <img src="{% static 'images/icons/defaultprofileimage.png' %}" alt="">
                                    {% endif %}
                                  </div>
                                  <div class="right-content">
                                    <h4>{{ reply.user.get_full_name }}<span>{{ reply.created_at }}</span></h4>
                                    <p>{{ reply.body }}</p>
                                  </div>
                                </li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                        
                        

                      </ul>
                    </div>
                  </div>
                </div>
                {% if request.user.is_authenticated %}
                <div class="col-lg-12">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2 id='your_comment'>Your comment</h2>
                    </div>
                    <div class="content">
                      <form id="comment" action="#" method="post">
                        {% csrf_token %}
                        <div class="row">
                          <input type="hidden" id="parent_id" name="parent_id" value="">
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="body" rows="6" id="body" placeholder="Type your comment" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                  {% else %}
                    <a class="btn btn-danger" href="{% url 'account:login' %}">For sending comments, please log in</a>
                {% endif %}
                </div>
              </div>
            </div>
          </div>
          {% include "includes/sidebar.html" %}
        </div>
      </div>
    </section>
  <script>
      function set_value(id) {
          document.getElementById('parent_id').value = id;
          window.location.href = "#your_comment";
          document.getElementById('body').placeholder = "Type your reply";
      }
  </script>
{% endblock content %}


    

blog/templates/blog/articles_list.html
{% extends "home_app/base.html" %}
{% load static %}


{% block content %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="text-content">
                  <h4>Recent Posts</h4>
                  <h2>Our Recent Blog Entries</h2>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      
      <!-- Banner Ends Here -->
  
      <section class="call-to-action">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="main-content">
                <div class="row">
                  <div class="col-lg-8">
                    <span>Stand Blog HTML5 Template</span>
                    <h4>Creative HTML Template For Bloggers!</h4>
                  </div>
                  <div class="col-lg-4">
                    <div class="main-button">
                      <a href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download Now!</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
  
  
      <section class="blog-posts grid-system">
        <div class="container">
          <div class="row">
            <div class="col-lg-8">
              <div class="all-blog-posts">
                <div class="row">
                  {% for article in articles %}
                  <div class="col-lg-6">
                    <div class="blog-post">
                      <div class="blog-thumb">
                        <img src="{{ article.image.url }}" alt="">
                      </div>
                      <div class="down-content">
                        <span>{{ article.category.all.first }}</span>
                        <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                        <ul class="post-info">
                          <li><a href="#">{{ article.author.get_full_name }}</a></li>
                          <li><a href="#">{{ article.created }}</a></li>
                          <li><a href="#">12 Comments</a></li>
                        </ul>
                        <p>{{ article.body }}</p>
                        <div class="post-options">
                          <div class="row">
                            <div class="col-lg-12">
                              <ul class="post-tags">
                                <li><i class="fa fa-tags"></i></li>
                                <li><a href="#">Best Templates</a>,</li>
                                <li><a href="#">TemplateMo</a></li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                  <div class="col-lg-12">
                    {% if articles.has_other_pages %}
                     <ul class="page-numbers">
                      {% if articles.has_previous %}
                        <li><a href="?page={{ articles.previous_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}"><i class="fa fa-angle-double-left"></i></a></li>
                      {% endif %}
                      
                      {% for i in articles.paginator.page_range %}
                          {% if articles.number == i %}
                              <li class="active"><a href="?page={{ i }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">{{ i }}</a></li>
                          {% else %}
                              <li><a href="?page={{ i }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">{{ i }}</a></li>
                          {% endif %}
                      {% endfor %}

                      {% if articles.has_next %}
                      <li><a href="?page={{ articles.next_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}"><i class="fa fa-angle-double-right"></i></a></li>
                      {% endif %}
                     </ul>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
            {% include "includes/sidebar.html" %}
          </div>
        </div>
      </section>
  

{% endblock %}

blog/templates/blog/articles_list2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of articles</title>
</head>
<body>
    {% for article in object_list %}
        <p>{{ article.title }}</p>
    {% endfor %}
</body>
</html>

blog/templates/blog/message_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete confirmation</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

blog/templates/blog/message_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Message List</title>
</head>
<body>
    {% for m in message_list %}
        <p>{{ m.title }} - {{ m.text|truncatewords:20 }} - {{ m.age }} - <span><a href="{% url "blog:message_edit" m.id %}">Edit</a></span></p>
    {% endfor %}
</body>
</html>

blog/templates/blog/message_update_form.html
{% extends "home_app/base.html" %}
{% load static %}
{% block title %}Message Update Form{% endblock %}
{% block content %}

<section class="contact-us">
    <div class="container">
      <div class="row">
      
        <div class="col-lg-12">
          <div class="down-contact">
            <div class="row">
              <div class="col-lg-8">
                <div class="sidebar-item contact-form">
                  <div class="sidebar-heading">
                    <h2>Update your message</h2>
                  </div>
                  <div class="content">
                    <form id="contact" action="" method="post">
                      {% csrf_token %}
                      <div class="row">
                        <div class="col-lg-12">

                            {{ form }}
                            <a href="{% url "blog:message_delete" object.id %}" class ="btn" btn-danger>Delete</a>

                        </div>
                        <div class="col-lg-12">
                          <fieldset>
                            <button type="submit" id="form-submit" class="main-button">Submit</button>
                          </fieldset>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="sidebar-item contact-information">
                  <div class="sidebar-heading">
                    <h2>contact information</h2>
                  </div>
                  <div class="content">
                    <ul>
                      <li>
                        <h5>090-484-8080</h5>
                        <span>PHONE NUMBER</span>
                      </li>
                      <li>
                        <h5>info@company.com</h5>
                        <span>EMAIL ADDRESS</span>
                      </li>
                      <li>
                        <h5>123 Aenean id posuere dui, 
                            <br>Praesent laoreet 10660</h5>
                        <span>STREET ADDRESS</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <div class="col-lg-12">
          <div id="map">
            <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>
        </div>
        
      </div>
    </div>
  </section>


{% endblock %}