account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("login", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("register", views.user_register, name="register"),
    path("edit", views.user_edit, name="edit"),
]

blog/urls.py
from django.urls import path
from . import views

# /articles/
app_name = "blog"
urlpatterns = [
    path('detail/<slug:slug>', views.article_detail, name="article_detail"),
    path('list', views.article_list, name="articles_list"),
    path('list2', views.ArticleList.as_view(), name="articles_list2"),
    path('category/<int:pk>', views.category_detail, name="category_detail"),
    path('search', views.search, name="search_articles"),
    path('contactus', views.contactus, name="contact_us"),
    path('testbase', views.TestBaseView.as_view(), name="test_base"),
    path('ali', views.HelloToAli.as_view(), name="test_ali"),
    path('karim', views.HelloToKarim.as_view(), name="test_karim"),
    path('users', views.UserList.as_view(), name="user_list"),
    path('red/<slug:slug>', views.HomePageRedirect.as_view(), name="redirect"),
    path('messages', views.MessageView.as_view(), name="messages"),
    path('message_list', views.MessagesListView.as_view(), name="message_list"),
    path('message/edit/<int:pk>', views.MessageUpdateView.as_view(), name="message_edit"),
    path('message/delete/<int:pk>', views.MessageDeleteView.as_view(), name="message_delete"),
    path('archive', views.ArchiveIndexArticleView.as_view(), name="archive"),
    path('archive/<int:year>', views.YearArchiveArticleView.as_view(), name="archive_year"),
    path('like/<slug:slug>/<int:pk>', views.like, name="like"),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('home_app.urls')),
    path('', include('account.urls')),
    path('articles/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from . import views

app_name = "home_app"
urlpatterns = [
    path("", views.home, name="main"),
    path("sidebar", views.sidebar, name="sidebar_partial"),
    path("about", views.about, name="about"),
]

home_app/models.py
from django.db import models

# Create your models here.

home_app/views.py
from django.shortcuts import render
from blog.models import Article
from django.urls import reverse

# Create your views here.

def home(request):
    articles = Article.objects.all()
    # articles = Article.custom_manager.all()
    # recent_articles = Article.objects.all()[:2]
    recent_articles = Article.objects.all().order_by('-created', '-updated')[:3]
    return render(request, "home_app/index.html", {"articles": articles}) #{"articles": articles, "recent_articles": recent_articles})
    

def sidebar(request):
    data = {'name': 'Ciawash'}
    return render(request, 'includes/sidebar.html', context=data)


def about(request):
    return render(request, "home_app/about.html", {})

home_app/templates/includes/footer.html
<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="social-icons">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Behance</a></li>
            <li><a href="#">Linkedin</a></li>
            <li><a href="#">Dribbble</a></li>
          </ul>
        </div>
        <div class="col-lg-12">
          <div class="copyright-text">
            <p>Copyright 2025 Stand Blog Co.
                  
               | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
          </div>
        </div>
      </div>
    </div>
  </footer>

home_app/templates/includes/footer_references.html
      {% load static %}
      <!-- Bootstrap core JavaScript -->
      <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
      <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  
      <!-- Additional Scripts -->
      <script src="{% static "js/custom.js" %}"></script>
      <script src="{% static "js/owl.js" %}"></script>
      <script src="{% static "js/slick.js" %}"></script>
      <script src="{% static "js/isotope.js" %}"></script>
      <script src="{% static "js/accordions.js" %}"></script>
      <script src="{% static "js/testajax.js" %}"></script>
      
      <script language = "text/Javascript"> 
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t){                   //declaring the array outside of the
        if(! cleared[t.id]){                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value='';         // with more chance of typos
            t.style.color='#fff';
            }
        }
      </script>

home_app/templates/includes/head_references.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="TemplateMo">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

<title>{% block title %}{% endblock %}</title>

<!-- Bootstrap core CSS -->
<link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">


<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
<link rel="stylesheet" href="{% static "css/templatemo-stand-blog.css" %}">
<link rel="stylesheet" href="{% static "css/owl.css" %}">

home_app/templates/includes/header.html
{% load static %}
    <!-- Header -->
    <header class="">
        <nav class="navbar navbar-expand-lg">
          <div class="container">
            <a class="navbar-brand" href=""><h2>Stand Blog<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item {% if request.resolver_match.url_name == 'main' %}active{% endif %}">
                  <a class="nav-link" href="{% url "home_app:main" %}">Home
                    <span class="sr-only">(current)</span>
                  </a>
                </li> 
                <li class="nav-item {% if request.resolver_match.url_name == 'about' %}active {% endif %}">
                  <a class="nav-link" href="{% url "home_app:about" %}">About Us</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'articles_list' %}active {% endif %}">
                  <a class="nav-link" href="{% url "blog:articles_list" %}">All Articles</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'post_details' %}active {% endif %}">
                  <a class="nav-link" href="post-details.html">Post Details</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'contact_us' %}active {% endif %}">
                  <a class="nav-link" href="{% url "blog:contact_us" %}">Contact Us</a>
                </li>
                <li class="nav-item">
                  {% if request.user.is_authenticated %}
                    <div class="d-flex">
                      {% if request.user.first_name %}
                        {% if user.profile.image %}
                          <span><img src="{{ user.profile.image.url }}" width="40px" height="40px" style="border-radius: 100%" alt=""></span>
                        {% else %}
                          <span><img src="{% static 'images/icons/defaultprofileimage.png' %}" width="40px" height="40px" style="border-radius: 100%" alt=""></span>
                        {% endif %}
                      <a class="nav-link" href="">{{ request.user.first_name }} {{ request.user.last_name }}</a>
                      {% else %}
                      <a class="nav-link" href="">{{ request.user.username }}</a>
                      {% endif %}
                      <a href="{% url 'account:logout' %}"><span class="badge badge-danger mt-2">logout</span></a>
                    </div>
                  {% else %}
                    <div class="d-flex">
                      <a class="nav-link" href="{% url 'account:login' %}" style=padding-right:0rem;>login    /</a><span class="mt-2"></span>
                      <a class="nav-link" href="{% url 'account:register' %}" style=padding-left:0.2rem;>register</a>
                    </div>  
                  {% endif %}
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>

home_app/templates/includes/sidebar.html
<div class="col-lg-4">
    <div class="sidebar">
      <div class="row">
        <div class="col-lg-12">
          <div class="sidebar-item search">
            <form id="search_form" name="gs" method="GET" action="{% url 'blog:search_articles' %}">
              <input type="text" name="q" class="searchText" placeholder="type to search..." autocomplete="on">
            </form>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="sidebar-item recent-posts">
            <div class="sidebar-heading">
              <h2>Recent Posts</h2>
            </div>
            <div class="content">
              <ul>
                {% for article in recent_articles %}
                <li><a href="{% url "blog:article_detail" article.slug %}">
                  <h5>{{ article.title }}</h5>
                  <span>{{ article.created }}</span>
                </a></li>
                {% endfor %}
                
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="sidebar-item categories">
            <div class="sidebar-heading">
              <h2>Categories</h2>
            </div>
            <div class="content">
              <ul>
                {% for cat in categories %}
                <li><a href="{% url "blog:category_detail" cat.id %}">{{ cat.title }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="sidebar-item tags">
            <div class="sidebar-heading">
              <h2>Tag Clouds</h2>
            </div>
            <div class="content">
              <ul>
                <li><a href="#">Lifestyle</a></li>
                <li><a href="#">Creative</a></li>
                <li><a href="#">HTML5</a></li>
                <li><a href="#">Inspiration</a></li>
                <li><a href="#">Motivation</a></li>
                <li><a href="#">PSD</a></li>
                <li><a href="#">Responsive</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>